// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuBvp4aluI4HUlQ7-S5LmikmeW161y19w',
    appId: '1:381777114942:web:65165ffad6e7d101d15e6f',
    messagingSenderId: '381777114942',
    projectId: 'chat-app-9c240',
    authDomain: 'chat-app-9c240.firebaseapp.com',
    storageBucket: 'chat-app-9c240.appspot.com',
    measurementId: 'G-6B6HKBGER4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LIZELu5kyzv0FvlQi_q5AUrclxtROCc',
    appId: '1:381777114942:android:ac245b978c49c61cd15e6f',
    messagingSenderId: '381777114942',
    projectId: 'chat-app-9c240',
    storageBucket: 'chat-app-9c240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFz54pXI0Yhac4xOdt4OaI-ng8T2a0oc',
    appId: '1:381777114942:ios:412a46b50330ec2fd15e6f',
    messagingSenderId: '381777114942',
    projectId: 'chat-app-9c240',
    storageBucket: 'chat-app-9c240.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAFz54pXI0Yhac4xOdt4OaI-ng8T2a0oc',
    appId: '1:381777114942:ios:90b8b1ae068b8bb8d15e6f',
    messagingSenderId: '381777114942',
    projectId: 'chat-app-9c240',
    storageBucket: 'chat-app-9c240.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
